### ISSUE TITLE
Test runtime upgrade to version-175

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#1057]
Refer to #887 

Here is the config file `config.yml` that we used to initial our network:
the current node-version on relaychain is v0.9.13, [link](https://github.com/paritytech/polkadot/releases/tag/v0.9.13)
the current node-version on parachain is v1.7.2-1, [link](https://github.com/parallel-finance/parallel/tree/v1.7.2-1)
the current wasm-version on parachain is v1.7.4. [link](https://github.com/parallel-finance/parallel/tree/v1.7.4)

```
relaychain:
  image: parity/polkadot:v0.9.13
  chain: rococo-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_frequency: 1
        validation_upgrade_delay: 1
  flags:
    - --rpc-methods=unsafe
    - --no-beefy
  nodes:
    - name: alice
    - name: bob
    - name: charlie

parachains:
  - image: parallelfinance/parallel:v1.7.4
    chain:
      base: heiko-dev
      collators:
        - alice
        - bob
        - charlie
      sudo: dave
    id: 2085
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --execution=wasm
    relaychainFlags:
      - --no-beefy
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie

```
