### ISSUE TITLE
Upgrade heiko to v178

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#1458]
Refer to #1318

**Comment by MrPai** [comment]
# Heiko Runtime Test

Here is the config file `config.yml` that we used to initial our network:
Current parachain node shows here[LIVE.md](https://github.com/parallel-finance/parallel/blob/47ae571f151cdd9ff071698ac27201a42a2cc82c/LIVE.md)
```
relaychain:
  image: parallelfinance/polkadot:v0.9.16
  chain: kusama-local
  env:
    RUST_LOG: xcm=trace
  flags:
    - --rpc-methods=unsafe
    - --wasm-execution=compiled
    - --execution=wasm
    - --state-cache-size=0
  nodes:
    - name: alice
    - name: bob
    - name: charlie
    - name: dave
parachains:
  - image: parallelfinance/parallel:v1.7.7
    chain:
      base: vanilla-dev
      collators:
        - alice
        - bob
        - charlie
      sudo: dave
    id: 2085
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
      - --state-cache-size=0
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
      - --state-cache-size=0
    env:
      RUST_LOG: xcm=trace,loans=trace,liquidStaking=trace,crowdloans=trace,amm=trace
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie
```
