### ISSUE TITLE
Upgrade Parallel to v181

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#1570]
Refer to #1483

**Comment by MrPai** [comment]
# Parallel Runtime Test

Here is the config file `config.yml` that we used to initial our network:
Current parachain node shows here [LIVE.md](https://github.com/parallel-finance/parallel/blob/f779877e6cd22aee322513bba1ef907c0dee5eb9/LIVE.md)
```
relaychain:
  image: parallelfinance/polkadot:v0.9.17
  chain: polkadot-local
  env:
    RUST_LOG: xcm=trace
  flags:
    - --rpc-methods=unsafe
    - --wasm-execution=compiled
    - --execution=wasm
    - --state-cache-size=0
  nodes:
    - name: alice
    - name: bob
    - name: charlie
    - name: dave
parachains:
  - image: parallelfinance/parallel:v1.7.7
    chain:
      base: parallel-dev
      collators:
        - alice
        - bob
        - charlie
      sudo: dave
    id: 2012
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
      - --state-cache-size=0
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
      - --state-cache-size=0
    env:
      RUST_LOG: xcm=trace,loans=trace,liquidStaking=trace,crowdloans=trace,amm=trace
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie
```
