### ISSUE TITLE
Upgrade Parallel to v184-2

### ISSUE THREAD

**Issue by yz89** [parallel-finance/parallel#1709]
Refer to #1617

**Comment by yz89** [comment]
# Heiko Runtime Test

Here is the config file `config.yml` that we used to initial our network:
Current parachain node shows here [LIVE.md](https://github.com/parallel-finance/parallel/blob/d40da2b380bc8c2b6c3ce0a40d9eea15eee93c8f/LIVE.md#heiko)
```
relaychain:
  image: parallelfinance/polkadot:v0.9.19
  chain: kusama-local
  env:
    RUST_LOG: xcm=trace
  flags:
    - --rpc-methods=unsafe
    - --wasm-execution=compiled
    - --execution=wasm
    - --state-cache-size=0
  nodes:
    - name: alice
    - name: bob
    - name: charlie
    - name: dave
parachains:
  - image: parallelfinance/parallel:v1.8.3
    chain:
      base: heiko-dev
      collators:
        - alice
        - bob
        - charlie
      sudo: dave
    id: 2085
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
      - --state-cache-size=0
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
      - --state-cache-size=0
    env:
      RUST_LOG: xcm=trace,loans=trace,liquidStaking=trace,crowdloans=trace,amm=trace
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie
```
