### ISSUE TITLE
Upgrade Parallel to v185-??

### ISSUE THREAD

**Issue by rjman-ljm** [parallel-finance/parallel#1746]
refer to #1709

**Comment by GopherJ** [comment]
should be v186, needs to bump version

**Comment by rjman-ljm** [comment]
okay, I'merge this [PR](https://github.com/parallel-finance/parallel/pull/1744) first, and then bump versions.

**Comment by rjman-ljm** [comment]
> 

tag: `v1.8.5-2` ?

**Comment by rjman-ljm** [comment]
# Parallel Runtime Upgrade Test

## Heiko Runtime Test

Here is the config file config.yml that we used to initial our network:
Current parachain node shows here [LIVE.md](https://github.com/parallel-finance/parallel/blob/stream-audit/LIVE.md)

<br/>

base: parallelfinance/parallel:v1.8.5-1

target [commit](https://github.com/parallel-finance/parallel/commit/3bc21fcc5b851f2c1d976786c350825ce82623f6)

<br/>

```yml
relaychain:
  image: parallelfinance/polkadot:v0.9.19
  chain: kusama-local
  env:
    RUST_LOG: xcm=trace
  flags:
    - --rpc-methods=unsafe
    - --wasm-execution=compiled
    - --execution=wasm
    - --state-cache-size=0
  nodes:
    - name: alice
    - name: bob
    - name: charlie
    - name: dave
parachains:
  - image: parallelfinance/parallel:v1.8.5-1
    chain:
      base: heiko-dev
      collators:
        - alice
        - bob
        - charlie
      sudo: dave
    id: 2085
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
      - --state-cache-size=0
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
      - --state-cache-size=0
    env:
      RUST_LOG: xcm=trace,loans=trace,liquidStaking=trace,crowdloans=trace,amm=trace
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie
```

### 1. Initial network

#### 1.1 Build docker config file

```sh
# use above config.yml, do not use config.yml in repo
$ sudo parachain-launch generate config.yml
$ sudo docker-compose -f output/docker-compose.yml up -d --build
```

#### 1.2  Parachain / Relaychain success produce blocks

![relay](https://cdn.jsdelivr.net/gh/rjman-ljm/resources@master/assets/16523591646551652359164384.png)

![para](https://cdn.jsdelivr.net/gh/rjman-ljm/resources@master/assets/16523596057921652359605654.png)

### 2. Initialize production

```sh
# parallel-finance/parallel/scripts/helper
yarn start launch --network heiko-dev
```

![prd-batch-all](https://cdn.jsdelivr.net/gh/rjman-ljm/resources@master/assets/16523603847511652360384568.png)

### 3. Runtime Upgrade

3.1 srtool build wasm

![srtool](attachment:28d9f3d63821f1e23f5472e17dd541e9)

3.2 parachainSystem.authorizedUpgrade

![upgrade-1](https://cdn.jsdelivr.net/gh/rjman-ljm/resources@master/assets/16523658519711652365851541.png)

3.3 parachainSystem.enactAuthorizedUpgrade

![upgrade-2](https://cdn.jsdelivr.net/gh/rjman-ljm/resources@master/assets/16523664200451652366419971.png)

3.4 success

![upgraded](https://cdn.jsdelivr.net/gh/rjman-ljm/resources@master/assets/16523663099781652366309691.png)

### Streaming test

Alice create stream

![1](https://cdn.jsdelivr.net/gh/rjman-ljm/resources@master/assets/16523668140621652366813750.png)

Bob withdraw stream

![2](https://cdn.jsdelivr.net/gh/rjman-ljm/resources@master/assets/16523668800151652366879199.png)

Charlie cancel stream

![3](https://cdn.jsdelivr.net/gh/rjman-ljm/resources@master/assets/16523668890101652366888295.png)

check storage

![4](https://cdn.jsdelivr.net/gh/rjman-ljm/resources@master/assets/16523669611861652366960954.png)

## Parallel Runtime Test
