### ISSUE TITLE
Test Runtime upgrade 196

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#1922]
config.yml
```
relaychain:
  image: parallelfinance/polkadot:v0.9.28
  chain: polkadot-local
  env:
    RUST_LOG: xcm=trace
  flags:
    - --rpc-methods=unsafe
    - --wasm-execution=compiled
    - --execution=wasm
    - --state-cache-size=0
  nodes:
    - name: alice
    - name: bob
    - name: charlie
    - name: dave
parachains:
  - image: parallelfinance/parallel:v1.9.4
    chain:
      base: parallel-dev
      collators:
        - alice
        - bob
        - charlie
      sudo: dave
    id: 2012
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --unsafe-rpc-external
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
      - --pruning=archive
      - --state-cache-size=0
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
      - --state-cache-size=0
    env:
      RUST_LOG: eth=trace,xcm=trace,loans=trace,liquidStaking=trace,crowdloans=trace,amm=trace,stableswap=trace,router=trace,bridge=trace,prices=trace
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie
```
