### ISSUE TITLE
Test storage migration and try runtime

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#676]
**Motivation**

Since parallel-heiko become a parachain of Kusama, it's better for us to use runtime-upgrade in our test network, so storage migration and try runtime is necessary.

**Suggested Solution**

- [x] test storage migration
- [x] test try-runtime
- [x] https://github.com/paritytech/substrate/issues/10407
- [x] test locally (need two times upgrade) 
- [ ] ~~test runtime upgrade on westend~~

**Comment by MrPai** [comment]
`./target/release/parallel try-runtime --execution wasm --chain heiko-dev on-runtime-upgrade live '--uri=wss://heiko-rpc.parallel.fi/'`

2021-12-01 12:53:49 assembling new collators for new session 0 at #0    
2021-12-01 12:53:49 assembling new collators for new session 1 at #0    
2021-12-01 12:53:49 scraping key-pairs from remote @ 0x3f80dd31f6df8ab5e5f64258adb27f808b407e99cc1040ceb2f6c9ad435475e6    
2021-12-01 12:53:49 downloading data for all pallets.    
2021-12-01 13:00:01 injecting a total of 32532 keys    
2021-12-01 13:00:04 found matching spec name: "heiko"    
2021-12-01 13:00:04 found matching spec version: 172    
2021-12-01 13:00:04 try-runtime::on_runtime_upgrade.    
2021-12-01 13:00:04 pre-migration, total accounts: 10680, one schedule: 10628, two schedule: 52, more schedule: 0, schedule need update: 10731, total_amount: 31450977794836396000    
2021-12-01 13:00:04 no need update vesting_schedule: <wasm:stripped>    
2021-12-01 13:00:04 ⚠️ System declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
2021-12-01 13:00:04 ✅ no migration for CurrencyAdapter    
2021-12-01 13:00:04 ✅ no migration for AMMRoute    
2021-12-01 13:00:04 ✅ no migration for AMM    
2021-12-01 13:00:04 ✅ no migration for ValidatorFeedersMembership    
2021-12-01 13:00:04 ✅ no migration for LiquidStakingAgentMembership    
2021-12-01 13:00:04 ✅ no migration for OracleMembership    
2021-12-01 13:00:04 ✅ no migration for TechnicalCommitteeMembership    
2021-12-01 13:00:04 ✅ no migration for GeneralCouncilMembership    
2021-12-01 13:00:04 ✅ no migration for NomineeElection    
2021-12-01 13:00:04 ✅ no migration for LiquidStaking    
2021-12-01 13:00:04 ✅ no migration for Prices    
2021-12-01 13:00:04 ✅ no migration for Loans    
2021-12-01 13:00:04 ✅ no migration for Vesting    
2021-12-01 13:00:04 ✅ no migration for OrmlXcm    
2021-12-01 13:00:04 ✅ no migration for XTokens    
2021-12-01 13:00:04 ✅ no migration for Oracle    
2021-12-01 13:00:04 ✅ no migration for AuraExt    
2021-12-01 13:00:04 ✅ no migration for Aura    
2021-12-01 13:00:04 ✅ no migration for Session    
2021-12-01 13:00:04 ✅ no migration for CollatorSelection    
2021-12-01 13:00:04 ✅ no migration for Authorship    
2021-12-01 13:00:04 ✅ no migration for CumulusXcm    
2021-12-01 13:00:04 ⚠️ PolkadotXcm declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
2021-12-01 13:00:04 ✅ no migration for DmpQueue    
2021-12-01 13:00:04 ✅ no migration for XcmpQueue    
2021-12-01 13:00:04 ✅ no migration for ParachainInfo    
2021-12-01 13:00:04 ✅ no migration for ParachainSystem    
2021-12-01 13:00:04 ✅ no migration for Scheduler    
2021-12-01 13:00:04 ✅ no migration for Treasury    
2021-12-01 13:00:04 ✅ no migration for TechnicalCommittee    
2021-12-01 13:00:04 ✅ no migration for GeneralCouncil    
2021-12-01 13:00:04 ✅ no migration for Democracy    
2021-12-01 13:00:04 ✅ no migration for Sudo    
2021-12-01 13:00:04 ✅ no migration for Proxy    
2021-12-01 13:00:04 ✅ no migration for Assets    
2021-12-01 13:00:04 ✅ no migration for TransactionPayment    
2021-12-01 13:00:04 ✅ no migration for Balances    
2021-12-01 13:00:04 ✅ no migration for Multisig    
2021-12-01 13:00:04 ✅ no migration for Utility    
2021-12-01 13:00:04 ✅ no migration for Timestamp    
2021-12-01 13:00:04 post-migration, total accounts: 10680, one schedule: 10628, two schedule: 52, more schedule: 0, schedule success update: 10731, total_amount: 31450977784297360000    
2021-12-01 13:00:04 TryRuntime_on_runtime_upgrade executed without errors. Consumed weight = 1335100000000, total weight = 2000000000000 (0.66755)

**Comment by MrPai** [comment]
## 1 launch network
1.1 config.yml
```
relaychain:
  image: parallelfinance/polkadot:v0.9.12-1
  chain: kusama-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_frequency: 1
        validation_upgrade_delay: 1
  flags:
    - --rpc-methods=unsafe
    - --no-beefy
    - --wasm-execution=compiled
    - --execution=wasm
    - -lxcm=trace
  nodes:
    - name: alice
    - name: bob
    - name: charlie
    - name: dave

parachains:
  - image: parallelfinance/parallel:v1.7.2
    chain:
      base: heiko-dev
      collators:
        - alice
        - bob
        - charlie
      sudo: dave
    id: 2085
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
      - -lxcm=trace
      - -lloans=trace
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
      - --no-beefy
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie
```
1.2 start network
```
$ parachain-launch generate config.yml
# start the service
$ docker-compose -f output/docker-compose.yml up -d --build

# shutdown the service
$ docker-compose -f output/docker-compose.yml down
$ docker volume prune -f
$ docker network prune -f

```
