### ISSUE TITLE
test runtime upgrade-fix orml-vesting blockprovider

### ISSUE THREAD

**Issue by MrPai** [parallel-finance/parallel#887]
Refer to #625 #794 

Here is the config file config.yml that we used to initial our network:
the current node-version on relaychain is v0.9.12,
the current node-version on parachain is v1.7.2,
the current wasm-version on parachain is v1.7.1.

```
relaychain:
  image: parallelfinance/polkadot:v0.9.11
  chain: kusama-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_frequency: 1
        validation_upgrade_delay: 1
  flags:
    - --rpc-methods=unsafe
    - --no-beefy
    - -lxcm=trace
  nodes:
    - name: alice
    - name: bob
    - name: charlie

parachains:
  - image: parallelfinance/parallel:v1.7.1
    chain:
      base: heiko-dev
      collators:
        - alice
        - bob
        - charlie
      sudo: dave
    id: 2085
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - -lxcm=trace
    relaychainFlags:
      - --no-beefy
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie

```

**Comment by MrPai** [comment]
```
$ git checkout v1.7.1 && rm -fr resources/specs && make submodules
$ make PACKAGE=heiko-runtime wasm
```

**Comment by MrPai** [comment]
v1.7.2 wasm
0xf57b2d484fe3dec9a48cea6556494f8f74f4f3695832c370d38c57be917d9c22

**Comment by MrPai** [comment]
```
relaychain:
  image: parallelfinance/polkadot:v0.9.11
  chain: kusama-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_frequency: 1
        validation_upgrade_delay: 1
  flags:
    - --rpc-methods=unsafe
    - --no-beefy
    - -lxcm=trace
  nodes:
    - name: alice
    - name: bob
    - name: charlie

parachains:
  - image: parallelfinance/parallel:v1.7.1
    chain:
      base: heiko-dev
      collators:
        - alice
        - bob
        - charlie
      sudo: dave
    id: 2085
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - -lxcm=trace
    relaychainFlags:
      - --no-beefy
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie
```

**Comment by MrPai** [comment]
```
relaychain:
  image: parallelfinance/polkadot:v0.9.12
  chain: kusama-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_frequency: 1
        validation_upgrade_delay: 1
  flags:
    - --rpc-methods=unsafe
    - --no-beefy
    - -lxcm=trace
  nodes:
    - name: alice
    - name: bob
    - name: charlie

parachains:
  - image: parallelfinance/parallel:v1.7.1
    chain:
      base: heiko-dev
      collators:
        - alice
        - bob
        - charlie
      sudo: dave
    id: 2085
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - -lxcm=trace
    relaychainFlags:
      - --no-beefy
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie
```

**Comment by MrPai** [comment]
# start the service
$ docker-compose -f output/docker-compose.yml up -d --build

# shutdown the service
$ docker-compose -f output/docker-compose.yml down
$ docker volume prune -f
$ docker network prune -f

**Comment by MrPai** [comment]
```
relaychain:
  image: parallelfinance/polkadot:v0.9.12-1
  chain: kusama-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_frequency: 1
        validation_upgrade_delay: 1
  flags:
    - --rpc-methods=unsafe
    - --no-beefy
    - -lxcm=trace
  nodes:
    - name: alice
    - name: bob
    - name: charlie

parachains:
  - image: parallelfinance/parallel:v1.7.2
    chain:
      base: heiko-dev
      collators:
        - alice
        - bob
        - charlie
      sudo: dave
    id: 2085
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - -lxcm=trace
    relaychainFlags:
      - --no-beefy
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie
```

**Comment by MrPai** [comment]
```
relaychain:
  image: parallelfinance/polkadot:v0.9.12
  chain: kusama-local
  runtimeGenesisConfig:
    configuration:
      config:
        validation_upgrade_frequency: 1
        validation_upgrade_delay: 1
  flags:
    - --rpc-methods=unsafe
    - --no-beefy
    - --wasm-execution=compiled
    - --execution=wasm
    - -lxcm=trace
  nodes:
    - name: alice
    - name: bob
    - name: charlie
    - name: dave

parachains:
  - image: parallelfinance/parallel:latest
    chain:
      base: vanilla-dev
      collators:
        - alice
        - bob
        - charlie
      sudo: dave
    id: 2085
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
      - -lxcm=trace
      - -lloans=trace
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
      - --no-beefy
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie

  - image: parallelfinance/polkadot-collator:v0.9.12
    chain:
      base: statemine-dev
      collators:
        - alice
        - bob
        - charlie
      sudo: dave
    id: 1000
    parachain: true
    flags:
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
    relaychainFlags:
      - --wasm-execution=compiled
      - --execution=wasm
      - --no-beefy
    nodes:
      - flags:
          - --alice
      - flags:
          - --bob
      - flags:
          - --charlie
```
